db2 "CONNECT TO ODLLAB1"

db2 "CREATE TABLESPACE TS_REC1"

db2 "CREATE TABLE APP.REC_T1 (
  ID BIGINT NOT NULL PRIMARY KEY,
  TXT VARCHAR(200),
  CREATED_TS TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP
) IN TS_REC1"

db2 "INSERT INTO APP.REC_T1(ID, TXT) VALUES (1,'before-incident')"
db2 "COMMIT"



db2 "BACKUP DATABASE ODLLAB1 ONLINE TABLESPACE (TS_REC1) TO /ars/data/backup/ODLLAB1 COMPRESS INCLUDE LOGS"
db2 "LIST HISTORY BACKUP ALL FOR ODLLAB1"


db2 "INSERT INTO APP.REC_T1(ID, TXT) VALUES (2,'after-backup')"
db2 "COMMIT"

# incident:
db2 "DELETE FROM APP.REC_T1 WHERE ID=2"
db2 "COMMIT"


# replace <TS> with the timestamp from LIST HISTORY
db2 "RESTORE DATABASE ODLLAB1 TABLESPACE (TS_REC1) FROM /ars/data/backup/ODLLAB1 TAKEN AT <TS>"


a
db2 "ROLLFORWARD DATABASE ODLLAB1 TO <YYYY-MM-DD-HH.MM.SS> TABLESPACE (TS_REC1) AND COMPLETE"

b
db2 "ROLLFORWARD DATABASE ODLLAB1 TO END OF LOGS TABLESPACE (TS_REC1) AND COMPLETE"


db2 "SELECT * FROM APP.REC_T1 ORDER BY ID"
db2 "LIST TABLESPACES SHOW DETAIL"


