db2 "CONNECT TO ODLLAB1"
db2 "CREATE TABLESPACE TS_DATA"

db2 "CREATE SCHEMA APP"

db2 "CREATE TABLE APP.TEST1 (
  ID BIGINT NOT NULL PRIMARY KEY,
  TXT VARCHAR(200),
  CREATED_TS TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP
) IN TS_DATA"

db2 "INSERT INTO APP.TEST1(ID, TXT) VALUES (1, 'hello')"
db2 "INSERT INTO APP.TEST1(ID, TXT) VALUES (2, 'db2 lab')"
db2 "COMMIT"

db2 "SELECT * FROM APP.TEST1 ORDER BY ID"

