export DB=ODLLAB1

db2 "CONNECT TO ${DB}"
db2 "SELECT COUNT(*) AS ROWS, MAX(ID) AS MAX_ID FROM APP.TEST1"
db2 "TERMINATE"

export DB=ODLLAB1

db2 "CONNECT TO ${DB}"
db2 "BACKUP DATABASE ${DB} ONLINE TO /ars/data/backup/${DB} COMPRESS INCLUDE LOGS"
db2 "TERMINATE"

export DB=ODLLAB1

db2 "CONNECT TO ${DB}"
db2 "BACKUP DATABASE ${DB} ONLINE TO /ars/data/backup/${DB} COMPRESS"
db2 "TERMINATE"

export DB=ODLLAB1

db2 "CONNECT TO ${DB}"
db2 "INSERT INTO APP.TEST1(ID, TXT) VALUES (3, 'after online backup')"
db2 "COMMIT"
db2 "SELECT * FROM APP.TEST1 ORDER BY ID"
db2 "TERMINATE"

db2 "CONNECT TO ${DB}"
db2 "ARCHIVE LOG FOR DATABASE ${DB}"
db2 "TERMINATE"

ls -l /ars/data/alog/${DB} | tail

export DB=ODLLAB1
db2 "DEACTIVATE DB ${DB}" || true
db2 "DROP DATABASE ${DB}"

export DB=ODLLAB1
export TS_ONLINE=<PUT_THE_ONLINE_BACKUP_TIMESTAMP_HERE>

db2 "RESTORE DATABASE ${DB} FROM /ars/data/backup/${DB} TAKEN AT ${TS_ONLINE}"

db2 "ROLLFORWARD DATABASE ${DB} TO END OF LOGS AND COMPLETE"

db2 "ACTIVATE DB ${DB}"
db2 "CONNECT TO ${DB}"

db2 "SELECT * FROM APP.TEST1 ORDER BY ID"

db2 "TERMINATE"

